version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpw
      POSTGRES_DB: moviedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://admin:adminpw@postgres:5432/moviedb
      MONGO_URL: mongodb://mongo:27017/moviedb
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - mongo
      - redis
    ports:
      - "3001:3001"
    volumes:
      - ./media:/usr/src/app/media # mount thư mục media nếu backend xử lý file
    # Cần chỉnh sửa entrypoint/backend nếu truy cập file video trực tiếp

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
  mongodb: